#! /bin/sh

. $srcdir/tests/test-lib.sh

check 'richacl-apply-masks everyone@:rwpxd::allow' <<EOF
everyone@:rwpxd::allow
EOF

check 'richacl-apply-masks -m 644 everyone@:rwpxd::allow' <<EOF
owner@:rwp::allow
everyone@:r::allow
EOF

check 'richacl-apply-masks -d -m 755 everyone@:rwpxd::allow' <<EOF
owner@:rwpxd::allow
everyone@:rx::allow
EOF

check 'richacl-apply-masks -m 640 everyone@:rwpxd::allow' <<EOF
owner@:rwp::allow
group@:r::allow
EOF

check 'richacl-apply-masks -m 644 group@:wpd::deny,everyone@:rwpxd::allow' <<EOF
owner@:rwp::allow
group@:wpd::deny
everyone@:r::allow
EOF

check 'richacl-apply-masks -m 640 group@:wpd::deny,everyone@:rwpxd::allow' <<EOF
owner@:rwp::allow
group@:wpd::deny
group@:r::allow
EOF

owner=`id -u`
check "richacl-apply-masks -m 640 owner@:rwp::allow,$owner:rwpx::allow,group@:rwpx::allow" <<EOF
owner@:rwp::allow
$owner:rwp::allow
group@:r::allow
EOF

check 'richacl-apply-masks -m 0 everyone@:rwpxd::allow' <<EOF
EOF

check 'richacl-apply-masks -m 664 1234:w::deny,everyone@:rw::allow' <<EOF
owner@:rwp::allow
1234:w::deny
group@:rw::allow
everyone@:r::allow
EOF
